# Generated by Django 5.1.7 on 2025-03-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('member_id', models.IntegerField()),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
